[package]
name = "conc"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"

[dev-dependencies]
big_s = "1.0.2"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
use_self = "deny"

[lints.clippy]
pedantic = { priority = -1, level = "deny" }
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
