[package]
name = "conc"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"

[dev-dependencies]
big_s = "1.0.2"

[profile.release]
opt-level = 's' # Optimize for size
lto = true # enable link-time optimization (removes dead code)
codegen-units = 1 # reduce codegen units to enable additional optimizations
panic = "unwind"
