name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.RELEASE_TOKEN }}

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          - filename: conc_linux_arm_64
            target: aarch64-unknown-linux-gnu
            os: ubuntu-22.04
          - filename: conc_linux_intel_64
            target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
          - filename: conc_macos_arm_64
            target: aarch64-apple-darwin
            os: macos-latest
          - filename: conc_macos_intel_64
            target: x86_64-apple-darwin
            os: macos-latest
          - filename: conc_windows_intel_64
            target: x86_64-pc-windows-msvc
            os: windows-latest
          - filename: conc_windows_arm_64
            target: aarch64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          archive: ${{ matrix.filename }}
          # (required) Comma-separated list of binary names (non-extension portion of filename) to build and upload.
          # Note that glob pattern is not supported yet.
          bin: conc
          # (optional) Target triple, default is host triple.
          target: ${{ matrix.target }}
          # (required) GitHub token for uploading assets to GitHub Releases.
          token: ${{ secrets.RELEASE_TOKEN }}
